apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        # 初始占位，流水线会自动替换为commit短哈希
        image: mac-cai/hello-go:init
        imagePullPolicy: Always